name: FlujoTrabajo

on: [push]

jobs:
  prueba1:
    runs-on: ubuntu-latest

    services:
       mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

    steps:

    - name: checkout
      uses: actions/checkout@v2
    - name: Listar archivos
      run: ls -la